/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/zshi-redhat/kube-ptp-daemon/pkg/apis/ptp/v1"
	scheme "github.com/zshi-redhat/kube-ptp-daemon/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodePTPConvesGetter has a method to return a NodePTPConfInterface.
// A group's client should implement this interface.
type NodePTPConvesGetter interface {
	NodePTPConves(namespace string) NodePTPConfInterface
}

// NodePTPConfInterface has methods to work with NodePTPConf resources.
type NodePTPConfInterface interface {
	Create(*v1.NodePTPConf) (*v1.NodePTPConf, error)
	Update(*v1.NodePTPConf) (*v1.NodePTPConf, error)
	UpdateStatus(*v1.NodePTPConf) (*v1.NodePTPConf, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.NodePTPConf, error)
	List(opts metav1.ListOptions) (*v1.NodePTPConfList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodePTPConf, err error)
	NodePTPConfExpansion
}

// nodePTPConves implements NodePTPConfInterface
type nodePTPConves struct {
	client rest.Interface
	ns     string
}

// newNodePTPConves returns a NodePTPConves
func newNodePTPConves(c *PtpV1Client, namespace string) *nodePTPConves {
	return &nodePTPConves{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodePTPConf, and returns the corresponding nodePTPConf object, and an error if there is any.
func (c *nodePTPConves) Get(name string, options metav1.GetOptions) (result *v1.NodePTPConf, err error) {
	result = &v1.NodePTPConf{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodeptpconves").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodePTPConves that match those selectors.
func (c *nodePTPConves) List(opts metav1.ListOptions) (result *v1.NodePTPConfList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.NodePTPConfList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodeptpconves").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodePTPConves.
func (c *nodePTPConves) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodeptpconves").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a nodePTPConf and creates it.  Returns the server's representation of the nodePTPConf, and an error, if there is any.
func (c *nodePTPConves) Create(nodePTPConf *v1.NodePTPConf) (result *v1.NodePTPConf, err error) {
	result = &v1.NodePTPConf{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodeptpconves").
		Body(nodePTPConf).
		Do().
		Into(result)
	return
}

// Update takes the representation of a nodePTPConf and updates it. Returns the server's representation of the nodePTPConf, and an error, if there is any.
func (c *nodePTPConves) Update(nodePTPConf *v1.NodePTPConf) (result *v1.NodePTPConf, err error) {
	result = &v1.NodePTPConf{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodeptpconves").
		Name(nodePTPConf.Name).
		Body(nodePTPConf).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *nodePTPConves) UpdateStatus(nodePTPConf *v1.NodePTPConf) (result *v1.NodePTPConf, err error) {
	result = &v1.NodePTPConf{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodeptpconves").
		Name(nodePTPConf.Name).
		SubResource("status").
		Body(nodePTPConf).
		Do().
		Into(result)
	return
}

// Delete takes name of the nodePTPConf and deletes it. Returns an error if one occurs.
func (c *nodePTPConves) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodeptpconves").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodePTPConves) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodeptpconves").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched nodePTPConf.
func (c *nodePTPConves) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodePTPConf, err error) {
	result = &v1.NodePTPConf{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodeptpconves").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
