/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/zshi-redhat/kube-ptp-daemon/pkg/apis/ptp/v1"
	scheme "github.com/zshi-redhat/kube-ptp-daemon/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodePTPDevsGetter has a method to return a NodePTPDevInterface.
// A group's client should implement this interface.
type NodePTPDevsGetter interface {
	NodePTPDevs(namespace string) NodePTPDevInterface
}

// NodePTPDevInterface has methods to work with NodePTPDev resources.
type NodePTPDevInterface interface {
	Create(*v1.NodePTPDev) (*v1.NodePTPDev, error)
	Update(*v1.NodePTPDev) (*v1.NodePTPDev, error)
	UpdateStatus(*v1.NodePTPDev) (*v1.NodePTPDev, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.NodePTPDev, error)
	List(opts metav1.ListOptions) (*v1.NodePTPDevList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodePTPDev, err error)
	NodePTPDevExpansion
}

// nodePTPDevs implements NodePTPDevInterface
type nodePTPDevs struct {
	client rest.Interface
	ns     string
}

// newNodePTPDevs returns a NodePTPDevs
func newNodePTPDevs(c *PtpV1Client, namespace string) *nodePTPDevs {
	return &nodePTPDevs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodePTPDev, and returns the corresponding nodePTPDev object, and an error if there is any.
func (c *nodePTPDevs) Get(name string, options metav1.GetOptions) (result *v1.NodePTPDev, err error) {
	result = &v1.NodePTPDev{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodeptpdevs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodePTPDevs that match those selectors.
func (c *nodePTPDevs) List(opts metav1.ListOptions) (result *v1.NodePTPDevList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.NodePTPDevList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodeptpdevs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodePTPDevs.
func (c *nodePTPDevs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodeptpdevs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a nodePTPDev and creates it.  Returns the server's representation of the nodePTPDev, and an error, if there is any.
func (c *nodePTPDevs) Create(nodePTPDev *v1.NodePTPDev) (result *v1.NodePTPDev, err error) {
	result = &v1.NodePTPDev{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodeptpdevs").
		Body(nodePTPDev).
		Do().
		Into(result)
	return
}

// Update takes the representation of a nodePTPDev and updates it. Returns the server's representation of the nodePTPDev, and an error, if there is any.
func (c *nodePTPDevs) Update(nodePTPDev *v1.NodePTPDev) (result *v1.NodePTPDev, err error) {
	result = &v1.NodePTPDev{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodeptpdevs").
		Name(nodePTPDev.Name).
		Body(nodePTPDev).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *nodePTPDevs) UpdateStatus(nodePTPDev *v1.NodePTPDev) (result *v1.NodePTPDev, err error) {
	result = &v1.NodePTPDev{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodeptpdevs").
		Name(nodePTPDev.Name).
		SubResource("status").
		Body(nodePTPDev).
		Do().
		Into(result)
	return
}

// Delete takes name of the nodePTPDev and deletes it. Returns an error if one occurs.
func (c *nodePTPDevs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodeptpdevs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodePTPDevs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodeptpdevs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched nodePTPDev.
func (c *nodePTPDevs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodePTPDev, err error) {
	result = &v1.NodePTPDev{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodeptpdevs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
