/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	ptpv1 "github.com/zshi-redhat/kube-ptp-daemon/pkg/apis/ptp/v1"
	versioned "github.com/zshi-redhat/kube-ptp-daemon/pkg/client/clientset/versioned"
	internalinterfaces "github.com/zshi-redhat/kube-ptp-daemon/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/zshi-redhat/kube-ptp-daemon/pkg/client/listers/ptp/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NodePTPCfgInformer provides access to a shared informer and lister for
// NodePTPCfgs.
type NodePTPCfgInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.NodePTPCfgLister
}

type nodePTPCfgInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNodePTPCfgInformer constructs a new informer for NodePTPCfg type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNodePTPCfgInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNodePTPCfgInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNodePTPCfgInformer constructs a new informer for NodePTPCfg type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNodePTPCfgInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PtpV1().NodePTPCfgs(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PtpV1().NodePTPCfgs(namespace).Watch(options)
			},
		},
		&ptpv1.NodePTPCfg{},
		resyncPeriod,
		indexers,
	)
}

func (f *nodePTPCfgInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNodePTPCfgInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *nodePTPCfgInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ptpv1.NodePTPCfg{}, f.defaultInformer)
}

func (f *nodePTPCfgInformer) Lister() v1.NodePTPCfgLister {
	return v1.NewNodePTPCfgLister(f.Informer().GetIndexer())
}
