/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	ptpv1 "github.com/zshi-redhat/kube-ptp-daemon/pkg/apis/ptp/v1"
	versioned "github.com/zshi-redhat/kube-ptp-daemon/pkg/client/clientset/versioned"
	internalinterfaces "github.com/zshi-redhat/kube-ptp-daemon/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/zshi-redhat/kube-ptp-daemon/pkg/client/listers/ptp/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NodePTPDevInformer provides access to a shared informer and lister for
// NodePTPDevs.
type NodePTPDevInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.NodePTPDevLister
}

type nodePTPDevInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNodePTPDevInformer constructs a new informer for NodePTPDev type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNodePTPDevInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNodePTPDevInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNodePTPDevInformer constructs a new informer for NodePTPDev type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNodePTPDevInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PtpV1().NodePTPDevs(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PtpV1().NodePTPDevs(namespace).Watch(options)
			},
		},
		&ptpv1.NodePTPDev{},
		resyncPeriod,
		indexers,
	)
}

func (f *nodePTPDevInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNodePTPDevInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *nodePTPDevInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ptpv1.NodePTPDev{}, f.defaultInformer)
}

func (f *nodePTPDevInformer) Lister() v1.NodePTPDevLister {
	return v1.NewNodePTPDevLister(f.Informer().GetIndexer())
}
