/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	ptpv1 "github.com/zshi-redhat/kube-ptp-daemon/pkg/apis/ptp/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodePTPConves implements NodePTPConfInterface
type FakeNodePTPConves struct {
	Fake *FakePtpV1
	ns   string
}

var nodeptpconvesResource = schema.GroupVersionResource{Group: "ptp.openshift.io", Version: "v1", Resource: "nodeptpconves"}

var nodeptpconvesKind = schema.GroupVersionKind{Group: "ptp.openshift.io", Version: "v1", Kind: "NodePTPConf"}

// Get takes name of the nodePTPConf, and returns the corresponding nodePTPConf object, and an error if there is any.
func (c *FakeNodePTPConves) Get(name string, options v1.GetOptions) (result *ptpv1.NodePTPConf, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodeptpconvesResource, c.ns, name), &ptpv1.NodePTPConf{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ptpv1.NodePTPConf), err
}

// List takes label and field selectors, and returns the list of NodePTPConves that match those selectors.
func (c *FakeNodePTPConves) List(opts v1.ListOptions) (result *ptpv1.NodePTPConfList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodeptpconvesResource, nodeptpconvesKind, c.ns, opts), &ptpv1.NodePTPConfList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &ptpv1.NodePTPConfList{ListMeta: obj.(*ptpv1.NodePTPConfList).ListMeta}
	for _, item := range obj.(*ptpv1.NodePTPConfList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodePTPConves.
func (c *FakeNodePTPConves) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodeptpconvesResource, c.ns, opts))

}

// Create takes the representation of a nodePTPConf and creates it.  Returns the server's representation of the nodePTPConf, and an error, if there is any.
func (c *FakeNodePTPConves) Create(nodePTPConf *ptpv1.NodePTPConf) (result *ptpv1.NodePTPConf, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodeptpconvesResource, c.ns, nodePTPConf), &ptpv1.NodePTPConf{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ptpv1.NodePTPConf), err
}

// Update takes the representation of a nodePTPConf and updates it. Returns the server's representation of the nodePTPConf, and an error, if there is any.
func (c *FakeNodePTPConves) Update(nodePTPConf *ptpv1.NodePTPConf) (result *ptpv1.NodePTPConf, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodeptpconvesResource, c.ns, nodePTPConf), &ptpv1.NodePTPConf{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ptpv1.NodePTPConf), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNodePTPConves) UpdateStatus(nodePTPConf *ptpv1.NodePTPConf) (*ptpv1.NodePTPConf, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nodeptpconvesResource, "status", c.ns, nodePTPConf), &ptpv1.NodePTPConf{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ptpv1.NodePTPConf), err
}

// Delete takes name of the nodePTPConf and deletes it. Returns an error if one occurs.
func (c *FakeNodePTPConves) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nodeptpconvesResource, c.ns, name), &ptpv1.NodePTPConf{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodePTPConves) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodeptpconvesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &ptpv1.NodePTPConfList{})
	return err
}

// Patch applies the patch and returns the patched nodePTPConf.
func (c *FakeNodePTPConves) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *ptpv1.NodePTPConf, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodeptpconvesResource, c.ns, name, pt, data, subresources...), &ptpv1.NodePTPConf{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ptpv1.NodePTPConf), err
}
