/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	ptpv1 "github.com/zshi-redhat/kube-ptp-daemon/pkg/apis/ptp/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodePTPDevs implements NodePTPDevInterface
type FakeNodePTPDevs struct {
	Fake *FakePtpV1
	ns   string
}

var nodeptpdevsResource = schema.GroupVersionResource{Group: "ptp.openshift.io", Version: "v1", Resource: "nodeptpdevs"}

var nodeptpdevsKind = schema.GroupVersionKind{Group: "ptp.openshift.io", Version: "v1", Kind: "NodePTPDev"}

// Get takes name of the nodePTPDev, and returns the corresponding nodePTPDev object, and an error if there is any.
func (c *FakeNodePTPDevs) Get(name string, options v1.GetOptions) (result *ptpv1.NodePTPDev, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodeptpdevsResource, c.ns, name), &ptpv1.NodePTPDev{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ptpv1.NodePTPDev), err
}

// List takes label and field selectors, and returns the list of NodePTPDevs that match those selectors.
func (c *FakeNodePTPDevs) List(opts v1.ListOptions) (result *ptpv1.NodePTPDevList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodeptpdevsResource, nodeptpdevsKind, c.ns, opts), &ptpv1.NodePTPDevList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &ptpv1.NodePTPDevList{ListMeta: obj.(*ptpv1.NodePTPDevList).ListMeta}
	for _, item := range obj.(*ptpv1.NodePTPDevList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodePTPDevs.
func (c *FakeNodePTPDevs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodeptpdevsResource, c.ns, opts))

}

// Create takes the representation of a nodePTPDev and creates it.  Returns the server's representation of the nodePTPDev, and an error, if there is any.
func (c *FakeNodePTPDevs) Create(nodePTPDev *ptpv1.NodePTPDev) (result *ptpv1.NodePTPDev, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodeptpdevsResource, c.ns, nodePTPDev), &ptpv1.NodePTPDev{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ptpv1.NodePTPDev), err
}

// Update takes the representation of a nodePTPDev and updates it. Returns the server's representation of the nodePTPDev, and an error, if there is any.
func (c *FakeNodePTPDevs) Update(nodePTPDev *ptpv1.NodePTPDev) (result *ptpv1.NodePTPDev, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodeptpdevsResource, c.ns, nodePTPDev), &ptpv1.NodePTPDev{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ptpv1.NodePTPDev), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNodePTPDevs) UpdateStatus(nodePTPDev *ptpv1.NodePTPDev) (*ptpv1.NodePTPDev, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nodeptpdevsResource, "status", c.ns, nodePTPDev), &ptpv1.NodePTPDev{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ptpv1.NodePTPDev), err
}

// Delete takes name of the nodePTPDev and deletes it. Returns an error if one occurs.
func (c *FakeNodePTPDevs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nodeptpdevsResource, c.ns, name), &ptpv1.NodePTPDev{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodePTPDevs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodeptpdevsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &ptpv1.NodePTPDevList{})
	return err
}

// Patch applies the patch and returns the patched nodePTPDev.
func (c *FakeNodePTPDevs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *ptpv1.NodePTPDev, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodeptpdevsResource, c.ns, name, pt, data, subresources...), &ptpv1.NodePTPDev{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ptpv1.NodePTPDev), err
}
