/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	ptpv1 "github.com/zshi-redhat/kube-ptp-daemon/pkg/apis/ptp/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodePTPCfgs implements NodePTPCfgInterface
type FakeNodePTPCfgs struct {
	Fake *FakePtpV1
	ns   string
}

var nodeptpcfgsResource = schema.GroupVersionResource{Group: "ptp.openshift.io", Version: "v1", Resource: "nodeptpcfgs"}

var nodeptpcfgsKind = schema.GroupVersionKind{Group: "ptp.openshift.io", Version: "v1", Kind: "NodePTPCfg"}

// Get takes name of the nodePTPCfg, and returns the corresponding nodePTPCfg object, and an error if there is any.
func (c *FakeNodePTPCfgs) Get(name string, options v1.GetOptions) (result *ptpv1.NodePTPCfg, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodeptpcfgsResource, c.ns, name), &ptpv1.NodePTPCfg{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ptpv1.NodePTPCfg), err
}

// List takes label and field selectors, and returns the list of NodePTPCfgs that match those selectors.
func (c *FakeNodePTPCfgs) List(opts v1.ListOptions) (result *ptpv1.NodePTPCfgList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodeptpcfgsResource, nodeptpcfgsKind, c.ns, opts), &ptpv1.NodePTPCfgList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &ptpv1.NodePTPCfgList{ListMeta: obj.(*ptpv1.NodePTPCfgList).ListMeta}
	for _, item := range obj.(*ptpv1.NodePTPCfgList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodePTPCfgs.
func (c *FakeNodePTPCfgs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodeptpcfgsResource, c.ns, opts))

}

// Create takes the representation of a nodePTPCfg and creates it.  Returns the server's representation of the nodePTPCfg, and an error, if there is any.
func (c *FakeNodePTPCfgs) Create(nodePTPCfg *ptpv1.NodePTPCfg) (result *ptpv1.NodePTPCfg, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodeptpcfgsResource, c.ns, nodePTPCfg), &ptpv1.NodePTPCfg{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ptpv1.NodePTPCfg), err
}

// Update takes the representation of a nodePTPCfg and updates it. Returns the server's representation of the nodePTPCfg, and an error, if there is any.
func (c *FakeNodePTPCfgs) Update(nodePTPCfg *ptpv1.NodePTPCfg) (result *ptpv1.NodePTPCfg, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodeptpcfgsResource, c.ns, nodePTPCfg), &ptpv1.NodePTPCfg{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ptpv1.NodePTPCfg), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNodePTPCfgs) UpdateStatus(nodePTPCfg *ptpv1.NodePTPCfg) (*ptpv1.NodePTPCfg, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nodeptpcfgsResource, "status", c.ns, nodePTPCfg), &ptpv1.NodePTPCfg{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ptpv1.NodePTPCfg), err
}

// Delete takes name of the nodePTPCfg and deletes it. Returns an error if one occurs.
func (c *FakeNodePTPCfgs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nodeptpcfgsResource, c.ns, name), &ptpv1.NodePTPCfg{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodePTPCfgs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodeptpcfgsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &ptpv1.NodePTPCfgList{})
	return err
}

// Patch applies the patch and returns the patched nodePTPCfg.
func (c *FakeNodePTPCfgs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *ptpv1.NodePTPCfg, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodeptpcfgsResource, c.ns, name, pt, data, subresources...), &ptpv1.NodePTPCfg{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ptpv1.NodePTPCfg), err
}
