---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodeptpdevs.ptp.openshift.io
spec:
  group: ptp.openshift.io
  version: v1
  names:
    kind: NodePTPDev
    listKind: NodePTPDevList
    plural: nodeptpdevs
    singular: nodeptpdev
  scope: Namespaced
  subresources:
    status: {}

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodeptpcfgs.ptp.openshift.io
spec:
  group: ptp.openshift.io
  version: v1
  names:
    kind: NodePTPCfg
    listKind: NodePTPCfgList
    plural: nodeptpcfgs
    singular: nodeptpcfg
  scope: Namespaced
  subresources:
    status: {}
