---
apiVersion: v1
kind: Namespace
metadata:
  name: ptp
  labels:
    name: ptp

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ptp-daemon-sa
  namespace: ptp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ptp-daemon-cluster-role
rules:
- apiGroups:
  - ""
  - k8s.cni.cncf.io
  resources:
  - nodes
  - pods
  - network-attachment-definitions
  verbs:
  - '*'
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  verbs:
  - '*'
- apiGroups:
  - ptp.openshift.io
  resources:
  - nodeptpstatuses
  verbs:
  - '*'

- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ptp-daemon-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ptp-daemon-cluster-role
subjects:
- kind: ServiceAccount
  name: ptp-daemon-sa
  namespace: ptp

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ptp-daemon
  namespace: ptp
spec:
  selector:
    matchLabels:
      app: ptp-daemon
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ptp-daemon
    spec:
      hostNetwork: true
      hostPID: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      serviceAccountName: ptp-daemon-sa
      containers:
      - name: ptp-container
        securityContext:
          privileged: true
        image: zenghui/ptp
        imagePullPolicy: IfNotPresent
        env:
        - name: PTP_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
