apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodeptpconfigs.ptp.openshift.io
spec:
  group: ptp.openshift.io
  names:
    kind: NodePTPStatus
    listKind: NodePTPStatusList
    plural: nodeptpconfigs
    singular: nodeptpconfig
  scope: Namespaced
