// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePTPDev) DeepCopyInto(out *NodePTPDev) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePTPDev.
func (in *NodePTPDev) DeepCopy() *NodePTPDev {
	if in == nil {
		return nil
	}
	out := new(NodePTPDev)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePTPDev) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePTPDevList) DeepCopyInto(out *NodePTPDevList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodePTPDev, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePTPDevList.
func (in *NodePTPDevList) DeepCopy() *NodePTPDevList {
	if in == nil {
		return nil
	}
	out := new(NodePTPDevList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePTPDevList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePTPDevSpec) DeepCopyInto(out *NodePTPDevSpec) {
	*out = *in
	if in.PTPDevices != nil {
		in, out := &in.PTPDevices, &out.PTPDevices
		*out = make([]PTPDevice, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePTPDevSpec.
func (in *NodePTPDevSpec) DeepCopy() *NodePTPDevSpec {
	if in == nil {
		return nil
	}
	out := new(NodePTPDevSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePTPDevStatus) DeepCopyInto(out *NodePTPDevStatus) {
	*out = *in
	if in.PTPDevices != nil {
		in, out := &in.PTPDevices, &out.PTPDevices
		*out = make([]PTPDevice, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePTPDevStatus.
func (in *NodePTPDevStatus) DeepCopy() *NodePTPDevStatus {
	if in == nil {
		return nil
	}
	out := new(NodePTPDevStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PTPDevice) DeepCopyInto(out *PTPDevice) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PTPDevice.
func (in *PTPDevice) DeepCopy() *PTPDevice {
	if in == nil {
		return nil
	}
	out := new(PTPDevice)
	in.DeepCopyInto(out)
	return out
}
