// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeMatchList) DeepCopyInto(out *NodeMatchList) {
	*out = *in
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = new(string)
		**out = **in
	}
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeMatchList.
func (in *NodeMatchList) DeepCopy() *NodeMatchList {
	if in == nil {
		return nil
	}
	out := new(NodeMatchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePTPCfg) DeepCopyInto(out *NodePTPCfg) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePTPCfg.
func (in *NodePTPCfg) DeepCopy() *NodePTPCfg {
	if in == nil {
		return nil
	}
	out := new(NodePTPCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePTPCfg) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePTPCfgList) DeepCopyInto(out *NodePTPCfgList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodePTPCfg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePTPCfgList.
func (in *NodePTPCfgList) DeepCopy() *NodePTPCfgList {
	if in == nil {
		return nil
	}
	out := new(NodePTPCfgList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePTPCfgList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePTPCfgSpec) DeepCopyInto(out *NodePTPCfgSpec) {
	*out = *in
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = make([]NodePTPProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Recommend != nil {
		in, out := &in.Recommend, &out.Recommend
		*out = make([]NodePTPRecommend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePTPCfgSpec.
func (in *NodePTPCfgSpec) DeepCopy() *NodePTPCfgSpec {
	if in == nil {
		return nil
	}
	out := new(NodePTPCfgSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePTPCfgStatus) DeepCopyInto(out *NodePTPCfgStatus) {
	*out = *in
	if in.MatchList != nil {
		in, out := &in.MatchList, &out.MatchList
		*out = make([]NodeMatchList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePTPCfgStatus.
func (in *NodePTPCfgStatus) DeepCopy() *NodePTPCfgStatus {
	if in == nil {
		return nil
	}
	out := new(NodePTPCfgStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePTPDev) DeepCopyInto(out *NodePTPDev) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePTPDev.
func (in *NodePTPDev) DeepCopy() *NodePTPDev {
	if in == nil {
		return nil
	}
	out := new(NodePTPDev)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePTPDev) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePTPDevList) DeepCopyInto(out *NodePTPDevList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodePTPDev, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePTPDevList.
func (in *NodePTPDevList) DeepCopy() *NodePTPDevList {
	if in == nil {
		return nil
	}
	out := new(NodePTPDevList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePTPDevList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePTPDevSpec) DeepCopyInto(out *NodePTPDevSpec) {
	*out = *in
	if in.PTPDevices != nil {
		in, out := &in.PTPDevices, &out.PTPDevices
		*out = make([]PTPDevice, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePTPDevSpec.
func (in *NodePTPDevSpec) DeepCopy() *NodePTPDevSpec {
	if in == nil {
		return nil
	}
	out := new(NodePTPDevSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePTPDevStatus) DeepCopyInto(out *NodePTPDevStatus) {
	*out = *in
	if in.PTPDevices != nil {
		in, out := &in.PTPDevices, &out.PTPDevices
		*out = make([]PTPDevice, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePTPDevStatus.
func (in *NodePTPDevStatus) DeepCopy() *NodePTPDevStatus {
	if in == nil {
		return nil
	}
	out := new(NodePTPDevStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePTPMatchRule) DeepCopyInto(out *NodePTPMatchRule) {
	*out = *in
	if in.NodeLabel != nil {
		in, out := &in.NodeLabel, &out.NodeLabel
		*out = new(string)
		**out = **in
	}
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePTPMatchRule.
func (in *NodePTPMatchRule) DeepCopy() *NodePTPMatchRule {
	if in == nil {
		return nil
	}
	out := new(NodePTPMatchRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePTPProfile) DeepCopyInto(out *NodePTPProfile) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Interface != nil {
		in, out := &in.Interface, &out.Interface
		*out = new(string)
		**out = **in
	}
	if in.Ptp4lOpts != nil {
		in, out := &in.Ptp4lOpts, &out.Ptp4lOpts
		*out = new(string)
		**out = **in
	}
	if in.Phc2sysOpts != nil {
		in, out := &in.Phc2sysOpts, &out.Phc2sysOpts
		*out = new(string)
		**out = **in
	}
	if in.Ptp4lConf != nil {
		in, out := &in.Ptp4lConf, &out.Ptp4lConf
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePTPProfile.
func (in *NodePTPProfile) DeepCopy() *NodePTPProfile {
	if in == nil {
		return nil
	}
	out := new(NodePTPProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePTPRecommend) DeepCopyInto(out *NodePTPRecommend) {
	*out = *in
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(string)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int64)
		**out = **in
	}
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make([]NodePTPMatchRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePTPRecommend.
func (in *NodePTPRecommend) DeepCopy() *NodePTPRecommend {
	if in == nil {
		return nil
	}
	out := new(NodePTPRecommend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PTPDevice) DeepCopyInto(out *PTPDevice) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PTPDevice.
func (in *PTPDevice) DeepCopy() *PTPDevice {
	if in == nil {
		return nil
	}
	out := new(PTPDevice)
	in.DeepCopyInto(out)
	return out
}
